# Generated by Django 3.0.8 on 2020-08-27 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_auto_20200827_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardproduct',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='restAPI.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
