# Generated by Django 3.0.8 on 2020-09-25 09:12

from django.db import migrations, models
import restAPI.models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0003_auto_20200920_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='http://127.0.0.1:8000/media/Samsung%20buds%2B/61AD9R7BnBL._AC_SX466__A4dveKA.jpg', upload_to=restAPI.models.foldername),
        ),
    ]
