# Generated by Django 3.0.8 on 2020-08-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_auto_20200809_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tottal_price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
