# Generated by Django 3.0.8 on 2020-08-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0004_auto_20200830_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restAPI.Category'),
        ),
    ]
