# Generated by Django 3.0.8 on 2020-10-21 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restAPI', '0006_auto_20201013_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='level',
        ),
        migrations.RemoveField(
            model_name='review',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='review',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='is_active',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('preparation', 'preparation')], default='active', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
    ]
